### ISSUE TITLE
`createrepo` doesn't exist in Ubuntu `20.04`

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/packaging#314]
### What feature do you want to see added?

I read in the [README.md](https://github.com/jenkinsci/packaging/blob/master/README.md) that 

> Running the main package script requires a Linux environment (currently Ubuntu)

I can also read that:

> Alternatively you can manually install the following onto a base install of Ubuntu:
> [...]
> createrepo

The thing is `createrepo` disappeared in `Ubuntu 20.04` and reappeared in another form in `Ubuntu 21.04`. It's now another package named `createrepo-c` because it has been rewritten in `C`.

Could we add the detection of the `Ubuntu` version we're running on, so that we can add the correct package?

I will make a PR to propose a draft `bash` implementation of the detection, and another one with the modified documentation.

**Comment by basil** [comment]
Solution without a clear problem.

If your high-level problem is that you are trying to build and test some arbitrary change to this repository on Ubuntu 20+, that would be one thing. (In fact, that is an unsupported build environment, as PR builds of this repository and release builds of `jenkins-infra/release` use the `jenkinsciinfra/packaging` Docker image, which is based on [Ubuntu 18.04](https://github.com/jenkins-infra/docker-packaging/blob/16929a338c88b7bb77169d3ff804c08bcd58590a/Dockerfile#L7-L9=), and for local development people are expected to use the same Docker image via https://github.com/jenkinsci/packaging/blob/416f402a884be8d33d4b665d149daada5e6b361b/README.md?plain=1#L36-L40=).

If your high-level problem is that you dislike the technical debt of depending on older versions of Ubuntu and want to upgrade our build toolchain as in https://github.com/jenkins-infra/docker-packaging/pull/28, that would be another thing. (At the time, that PR was blocked on some infrastructure prerequisites, which may in fact be ready now.)

If your high-level problem is something other than the above two problems, that would be another thing.

We will never know unless the ticket includes a clear description of the high-level problem you are trying to solve.

**Comment by gounthar** [comment]
My problem is that I'm trying to build and test some changes for the `armhf` platform on `Ubuntu 20`.
I have since then migrated to `Ubuntu 22.04` but I thought proposing something to other users that could be stuck with `Ubuntu 20.x` could help.
I was maybe wrong. I'm not a native English speaker, so I could misunderstand things.
Nevertheless, words are important, and I can't see **anywhere** in the documentation one **has** to use `docker` to build packages.
There is a _remark_ that a `docker`image is available to run the script, but it's not written it's mandatory to use it.
Furthermore, it's not written **anywhere** in that `README.md` that one **has** to use `Ubuntu 18.04`.

There is no doubt **you** have the knowledge about the ecosystem and how one is supposed to build these packages at home, but as a first time user, this **does not show** through the documentation.

I'll then close my issue and my PR and focus on modifying the documentation so that first time users don't hit the wall.

**Comment by basil** [comment]
> There is no doubt **you** have the knowledge about the ecosystem and how one is supposed to build these packages at home

But not as a result of having designed/implemented the existing system or being mentored by someone who did. Rather, I acquired this knowledge rather painfully without any onboarding while implementing some major enhancements last year. Are you able to do the same? In this regard, you clearly have an advantage since there is somebody around to assist you, whereas there was nobody around to assist me since the previous developer ceased activity without onboarding a replacement. Despite this disadvantage, I was successful in implementing a major enhancement that many others had failed to implement for several years. I wish you success in your endeavors as well.

You sound frustrated with the current state of the documentation. If you are this frustrated with the current (incomplete) state of the documentation, imagine how frustrated I was last year to discover that the documentation was not only incomplete but _actively wrong_ in some areas. I wasted days before coming up with #231.

With #231 I left the documentation (slightly) better than I found it. This is how open source software works. You see something you do not like, and you fix it. You can do the same thing by leaving the documentation better than you found it. But to do so _efficiently_ with other people requires clearly explaining the high-level problem you are trying to solve. Now that I understand your high-level problem more clearly, I can properly guide you.

> Nevertheless, words are important

So are actions. Reacting with a thumbs down emoji to those who are trying to help you, as you did at one point to https://github.com/jenkinsci/packaging/issues/314#issuecomment-1145088927, creates a negative atmosphere and will not motivate others to help you.

![Screenshot_20220602_114928](https://user-images.githubusercontent.com/29850/171718873-534c452c-51e0-4f3b-8b9c-8b51d85e7257.png)

Let us focus on the solution and the path forward without casting aspersions on the existing (admittedly flawed) state of affairs. In this way, we can leave the software in a better state than we found it and contribute positively for our own benefit and the benefit of the greater Jenkins community.

**Comment by gounthar** [comment]
Thank you for this detailed and sourced explanation. 
I will definitely submit changes to the documentation.
