### ISSUE TITLE
APT key exired on 2023-03-30

### ISSUE THREAD

**Issue by sebastic** [jenkinsci/packaging#383]
The GPG key used to sign the Debian package repo has expired:
```
Err:9 https://pkg.jenkins.io/debian-stable binary/ Release.gpg
  The following signatures were invalid: EXPKEYSIG FCEF32E745F2C3D5 Jenkins Project <jenkinsci-board@googlegroups.com>
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://pkg.jenkins.io/debian-stable binary/ Release: The following signatures were invalid: EXPKEYSIG FCEF32E745F2C3D5 Jenkins Project <jenkinsci-board@googlegroups.com>
W: Failed to fetch https://pkg.jenkins.io/debian-stable/binary/Release.gpg  The following signatures were invalid: EXPKEYSIG FCEF32E745F2C3D5 Jenkins Project <jenkinsci-board@googlegroups.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
```
$ wget https://pkg.jenkins.io/debian-stable/jenkins.io.key -P /tmp/
$ gpg /tmp/jenkins.io.key 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2020-03-30 [SC] [expired: 2023-03-30]
      62A9756BFD780C377CF24BA8FCEF32E745F2C3D5
uid           Jenkins Project <jenkinsci-board@googlegroups.com>
sub   rsa4096 2020-03-30 [E] [expired: 2023-03-30]
```

**Comment by sebastic** [comment]
Note that https://pkg.jenkins.io/debian-stable/ documents the `jenkins.io.key`, whereas https://www.jenkins.io/doc/book/installing/linux/#long-term-support-release documents the `jenkins.io-2023.key`.

The `jenkins.io-2023.key` key should be renamed to `jenkins.io.key` to keep the URL for the current key stable.

**Comment by sebastic** [comment]
Changing the URL for the current key is bad, you should reconsider that.

**Comment by MarkEWaite** [comment]
> Changing the URL for the current key is bad, you should reconsider that.

Saying that something "is bad" does not persuade most people.  Can you provide more details why you believe it is bad?  

I've seen suggestions in [JENKINS-70901](https://issues.jenkins.io/browse/JENKINS-70901) to sign the repository with multiple keys so that multiple keys are valid.  That seems like it would require multiple key files.  That same issue linked to an article that suggests that the primary package should have a separate package that installs the keyring for the application so that the keyring could be upgraded.  Happy to learn more about most effective ways to handle upgrades of expired PGP keys.

**Comment by sebastic** [comment]
Everyone needs to update the URL for the repo key in their config management systems.

Keeping the URL stable only requires users to run it again to add the updated key.
